version: "3"

services:
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping" ]
      interval: 10s
      timeout: 20s
      retries: 10
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - redis
    ports:
      - 8000:8000
    networks:
      - app-network

  scraper-worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - app-network
    env_file:
      - .env


volumes:
  redis_data:
    external: false
    name: "redis_data"

networks:
  app-network: